version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 21 e npm...
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - npm install --loglevel=error
      - REACT_APP_API_URL=http://localhost:3001 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo Rodando testes unitários e de integração...
      - npm test
      - echo Deploying application...
      - aws s3 sync ./client/build s3://bia-artifacts-804826263064
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
