version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "=== TESTE DE CONECTIVIDADE ==="
      - echo "1. Testando acesso ao Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id "rds!db-2e2b930b-62af-4b19-82ad-6d67abd06746" --query 'SecretString' --output text
      - echo "2. Testando conectividade com RDS..."
      - nc -zv bia-db.c4nckw8qytev.us-east-1.rds.amazonaws.com 5432 || echo "RDS não acessível"
      - echo "3. Testando acesso à internet..."
      - curl -I https://github.com || echo "GitHub não acessível"
      - echo "=== FIM DOS TESTES ==="
  build:
    commands:
      - echo "Build de teste concluído"
