version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    DB_NAME: postgres
    DB_SSL: "false"
  parameter-store:
    SECRET_ARN: /bia/secrets/rds-secret-arn
    DB_HOST: /bia/db/host

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - n 22.20.0
      - yum install -y jq
      - npm install
  pre_build:
    commands:
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$SECRET_ARN" --query 'SecretString' --output text)
      - export DB_USER=$(echo $SECRET_JSON | jq -r '.username')
      - export DB_PWD=$(echo $SECRET_JSON | jq -r '.password')
      - echo "Executando validações de PR..."
      - npm run lint
      - npm run db:test
      - npm test
      - npm run test:integration
  build:
    commands:
      - echo "✅ Todas as validações passaram!"    

